import type { Category } from './ui'

export type Provider = {
  id: string
  /** Accessible name for the tile — the artwork itself carries the wordmark. */
  name: string
  src: string
}

/**
 * Provider artwork per category, in the order the grid renders it: the
 * recognisable brands lead, the rest follow alphabetically. Re-rank by moving
 * an entry — array order is page order.
 */
export const PROVIDERS: Record<Category, Provider[]> = {
  slot: [
    { id: 'pgsoft', name: 'PG Soft', src: '/images/providers/slot/pgsoft.png' },
    { id: 'pp', name: 'Pragmatic Play', src: '/images/providers/slot/pp.png' },
    { id: 'jili', name: 'JILI', src: '/images/providers/slot/jili.png' },
    { id: 'haba', name: 'Habanero', src: '/images/providers/slot/haba.png' },
    { id: 'microgame', name: 'Microgaming', src: '/images/providers/slot/microgame.png' },
    { id: 'playtech', name: 'Playtech', src: '/images/providers/slot/playtech.png' },
    { id: 'redtiger', name: 'Red Tiger', src: '/images/providers/slot/redtiger.png' },
    { id: 'relax', name: 'Relax Gaming', src: '/images/providers/slot/relax.png' },
    { id: 'nolimitcity', name: 'Nolimit City', src: '/images/providers/slot/nolimitcity.png' },
    { id: 'evoplay', name: 'Evoplay', src: '/images/providers/slot/evoplay.png' },
    { id: 'live22', name: 'Live22', src: '/images/providers/slot/live22.png' },
    { id: 'fachai', name: 'FaChai', src: '/images/providers/slot/fachai.png' },
    { id: 'ka', name: 'KA Gaming', src: '/images/providers/slot/ka.png' },
    { id: 'bng', name: 'Booongo', src: '/images/providers/slot/bng.png' },
    { id: 'spinix', name: 'Spinix', src: '/images/providers/slot/spinix.png' },
    { id: 'ab', name: 'Allbet', src: '/images/providers/slot/ab.png' },
    { id: 'advantplay', name: 'AdvantPlay', src: '/images/providers/slot/advantplay.png' },
    { id: 'ae', name: 'AE Casino', src: '/images/providers/slot/ae.png' },
    { id: 'alize', name: 'Alize', src: '/images/providers/slot/alize.png' },
    { id: 'allbet', name: 'Allbet', src: '/images/providers/slot/allbet.png' },
    { id: 'amigo', name: 'Amigo', src: '/images/providers/slot/amigo.png' },
    { id: 'bg', name: 'BG Gaming', src: '/images/providers/slot/bg.png' },
    { id: 'blackants', name: 'Black Ants', src: '/images/providers/slot/blackants.png' },
    { id: 'btgaming', name: 'BT Gaming', src: '/images/providers/slot/btgaming.png' },
    { id: 'cherry', name: 'Cherry', src: '/images/providers/slot/cherry.png' },
    { id: 'dg', name: 'Dream Gaming', src: '/images/providers/slot/dg.png' },
    { id: 'dragoonsoft', name: 'DragoonSoft', src: '/images/providers/slot/dragoonsoft.png' },
    { id: 'ebet', name: 'eBET', src: '/images/providers/slot/ebet.png' },
    { id: 'evolution', name: 'Evolution', src: '/images/providers/slot/evolution.png' },
    { id: 'expanse', name: 'Expanse', src: '/images/providers/slot/expanse.png' },
    { id: 'fastspin', name: 'Fastspin', src: '/images/providers/slot/fastspin.png' },
    { id: 'fg', name: 'FG Gaming', src: '/images/providers/slot/fg.png' },
    { id: 'funky', name: 'Funky Games', src: '/images/providers/slot/funky.png' },
    { id: 'galaxsys', name: 'Galaxsys', src: '/images/providers/slot/galaxsys.png' },
    { id: 'gpi', name: 'GPI', src: '/images/providers/slot/gpi.png' },
    { id: 'gw', name: 'GW Gaming', src: '/images/providers/slot/gw.png' },
    { id: 'hg', name: 'HG Gaming', src: '/images/providers/slot/hg.png' },
    { id: 'hotdog', name: 'Hotdog Gaming', src: '/images/providers/slot/hotdog.png' },
    { id: 'jk', name: 'JK Gaming', src: '/images/providers/slot/jk.png' },
    { id: 'kingmaker', name: 'KingMaker', src: '/images/providers/slot/kingmaker.png' },
    { id: 'lottoexit', name: 'Lotto Exit', src: '/images/providers/slot/lottoexit.png' },
    { id: 'mangoplay', name: 'Mango Play', src: '/images/providers/slot/mangoplay.png' },
    { id: 'megawin', name: 'Megawin', src: '/images/providers/slot/megawin.png' },
    { id: 'mp', name: 'MP Gaming', src: '/images/providers/slot/mp.png' },
    { id: 'naga', name: 'Naga Games', src: '/images/providers/slot/naga.png' },
    { id: 'nextspin', name: 'NextSpin', src: '/images/providers/slot/nextspin.png' },
    { id: 'pinnacle', name: 'Pinnacle', src: '/images/providers/slot/pinnacle.png' },
    { id: 'ponymuah', name: 'Ponymuah', src: '/images/providers/slot/ponymuah.png' },
    { id: 'pretty', name: 'Pretty Gaming', src: '/images/providers/slot/pretty.png' },
    { id: 'ps', name: 'PS Gaming', src: '/images/providers/slot/ps.png' },
    { id: 'rbsevenslot', name: 'RB Seven Slot', src: '/images/providers/slot/rbsevenslot.png' },
    { id: 'rich', name: 'Rich88', src: '/images/providers/slot/rich.png' },
    { id: 'sa', name: 'SA Gaming', src: '/images/providers/slot/sa.png' },
    { id: 'spsg', name: 'SPSG', src: '/images/providers/slot/spsg.png' },
    { id: 'sw', name: 'SW Gaming', src: '/images/providers/slot/sw.png' },
    { id: 'titansoft', name: 'TitanSoft', src: '/images/providers/slot/titansoft.png' },
    { id: 'ts', name: 'TS Gaming', src: '/images/providers/slot/ts.png' },
    { id: 'uuslots', name: 'UU Slots', src: '/images/providers/slot/uuslots.png' },
    { id: 'vivo', name: 'Vivo Gaming', src: '/images/providers/slot/vivo.png' },
    { id: 'vplus', name: 'V Plus', src: '/images/providers/slot/vplus.png' },
    { id: 'we', name: 'WE Gaming', src: '/images/providers/slot/we.png' },
    { id: 'wgb', name: 'WGB', src: '/images/providers/slot/wgb.png' },
    { id: 'xg', name: 'XG Gaming', src: '/images/providers/slot/xg.png' },
  ],
  casino: [
    { id: 'evolution', name: 'Evolution', src: '/images/providers/casino/evolution.png' },
    { id: 'sexy', name: 'Sexy Gaming', src: '/images/providers/casino/sexy.png' },
    { id: 'pretty', name: 'Pretty Gaming', src: '/images/providers/casino/pretty.png' },
    { id: 'pp', name: 'Pragmatic Play', src: '/images/providers/casino/pp.png' },
    { id: 'playtech', name: 'Playtech', src: '/images/providers/casino/playtech.png' },
    { id: 'ae', name: 'AE Casino', src: '/images/providers/casino/ae.png' },
    { id: 'ab', name: 'Allbet', src: '/images/providers/casino/ab.png' },
    { id: 'bg', name: 'BG Gaming', src: '/images/providers/casino/bg.png' },
    { id: 'sw', name: 'SW Gaming', src: '/images/providers/casino/sw.png' },
    { id: 'astar', name: 'A-Star', src: '/images/providers/casino/astar.png' },
    { id: 'audi', name: 'Audi Casino', src: '/images/providers/casino/audi.png' },
    { id: 'cg', name: 'CQ9', src: '/images/providers/casino/cg.png' },
    { id: 'mangoplay', name: 'Mango Play', src: '/images/providers/casino/mangoplay.png' },
    { id: 'vivo', name: 'Vivo Gaming', src: '/images/providers/casino/vivo.png' },
    { id: 'wcasino', name: 'W Casino', src: '/images/providers/casino/wcasino.png' },
    { id: 'wm', name: 'WM Casino', src: '/images/providers/casino/wm.png' },
    { id: 'yeebet', name: 'Yeebet', src: '/images/providers/casino/yeebet.png' },
  ],
  sport: [
    { id: 'sbo', name: 'SBOBET', src: '/images/providers/sport/sbo.png' },
    { id: 'sabasport', name: 'SABA Sport', src: '/images/providers/sport/sabasport.png' },
    { id: 'newsportbook', name: 'New Sportbook', src: '/images/providers/sport/newsportbook.png' },
    { id: 'muaypukyok', name: 'Muay Pukyok', src: '/images/providers/sport/muaypukyok.png' },
    { id: 'threesing', name: 'Three Sing', src: '/images/providers/sport/threesing.png' },
  ],
  lotto: [
    { id: 'lsm99lotto', name: 'LSM99 Lotto', src: '/images/providers/lotto/lsm99lotto.png' },
    { id: 'luckylotto', name: 'Lucky Lotto', src: '/images/providers/lotto/luckylotto.png' },
    { id: 'iamlotto', name: 'I Am Lotto', src: '/images/providers/lotto/iamlotto.png' },
    { id: 'rbsevenlotto', name: 'RB Seven Lotto', src: '/images/providers/lotto/rbsevenlotto.png' },
    { id: 'lottoexit', name: 'Lotto Exit', src: '/images/providers/lotto/lottoexit.png' },
    { id: 'qqkeno', name: 'QQ Keno', src: '/images/providers/lotto/qqkeno.png' },
  ],
}
